// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-8YgkHNcsqa2GkeWXQNibhCA-wi5mToQ',
    appId: '1:323870926196:web:ded04cd6a4356e1277f821',
    messagingSenderId: '323870926196',
    projectId: 'unifunds-37e37',
    authDomain: 'unifunds-37e37.firebaseapp.com',
    storageBucket: 'unifunds-37e37.appspot.com',
    measurementId: 'G-TNNDTG98N8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfP8leYhPcx9_4hoOvSQ99Ee49rstaJmo',
    appId: '1:323870926196:android:d8eef6e2b97c02f277f821',
    messagingSenderId: '323870926196',
    projectId: 'unifunds-37e37',
    storageBucket: 'unifunds-37e37.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXQBWQpbeoTrXvppfUa8ipWbdvXAPVtm0',
    appId: '1:323870926196:ios:fc2305360b9ba68077f821',
    messagingSenderId: '323870926196',
    projectId: 'unifunds-37e37',
    storageBucket: 'unifunds-37e37.appspot.com',
    androidClientId: '323870926196-lblpflipgr9v73s4e2g7soo0od6182ep.apps.googleusercontent.com',
    iosClientId: '323870926196-cs86d4qf4st350sq7asm65tao27mfnm8.apps.googleusercontent.com',
    iosBundleId: 'com.example.uniFunds',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXQBWQpbeoTrXvppfUa8ipWbdvXAPVtm0',
    appId: '1:323870926196:ios:b0c90ec5a6d52ebb77f821',
    messagingSenderId: '323870926196',
    projectId: 'unifunds-37e37',
    storageBucket: 'unifunds-37e37.appspot.com',
    androidClientId: '323870926196-lblpflipgr9v73s4e2g7soo0od6182ep.apps.googleusercontent.com',
    iosClientId: '323870926196-97kr96tukfo8o267fmao45onaqs29j8o.apps.googleusercontent.com',
    iosBundleId: 'com.example.uniFunds.RunnerTests',
  );
}
